sudo: false

language: php
php:
  - 7

notifications:
  email:
    on_success: change
    on_failure: change

script:
  - cd ext/argon2 && CFLAGS="-fPIC" make && make test && rm libargon2.so && cd ../..
  - phpize
  - ./configure --with-argon2
  - NO_INTERACTION=true make test