sudo: false

language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

cache:
  directories:
    - ext/argon2

notifications:
  email:
    on_success: change
    on_failure: change

script:
  - cd ext/argon2 && CFLAGS="-fPIC" make -j1 OPTTARGET=i686 && make test && rm libargon2.so.1 && cd ../..
  - phpize
  - ./configure --with-argon2
  - NO_INTERACTION=true make test